
export const encouragement = {
    excellent: [
        "You're a superstar! ✨",
        "Perfect score! You're on fire! 🔥",
        "Wow! You absolutely nailed it!",
        "Incredible work! Are you a wizard? 🧙‍♂️",
        "You didn't just pass, you soared! 🚀",
        "That was amazing! You're a true champion.",
        "Aced it! You're basically a genius.",
        "You've got the magic touch! ✨",
        "Is there anything you can't do? Outstanding!",
        "This is the way. You have spoken.",
        "You're the GOAT! 🐐",
        "Flawless victory!",
        "You understood the assignment. A+!",
        "Your brain is officially huge. 🧠",
        "To infinity... and beyond! Great job!",
        "You're on top of the world!",
        "That was legendary!",
        "You're a knowledge ninja!",
        "Big brain energy!",
        "You've got this down to a science!",
        "You're unstoppable!",
        "That's how you do it!",
        "You're a rockstar!",
        "Top of the class!",
        "Simply brilliant!",
        "You're a mind marathoner!",
        "Exceptional performance!",
        "You've mastered this topic!",
        "Your focus is superhuman!",
        "You're a learning machine!",
        "I'm impressed! Seriously!",
        "You've unlocked a new level of smart!",
        "That was a 200 IQ play!",
        "You're in a league of your own!",
        "You didn't miss a beat!",
        "Consider this quiz... crushed.",
        "You're a titan of trivia!",
        "That was a masterclass performance.",
        "They should make a movie about how well you did.",
        "You're the chosen one!",
        "You've got more knowledge than a library!",
        "That was cleaner than a fresh pair of sneakers.",
        "You're a straight-up scholar!",
        "Mic drop. You're done. And you aced it.",
        "You're Basically a Superhero: Captain Know-It-All!",
        "Hulk, SMASH that quiz! And you did.",
        "You're smarter than Tony Stark.",
        "I see a future Avenger in you.",
        "You've got more answers than the Google search engine.",
        "You're the Luke Skywalker of learning!",
        "May the score be with you. And it was.",
        "You're a Jedi Master of this topic.",
        "This is the quiz you were looking for. And you aced it.",
        "You're a Pokémon Master of knowledge!",
        "You caught all the right answers!",
        "It's super effective! You won!",
        "You're a diamond-level player in this game of knowledge.",
        "You just earned the Victory Royale!",
        "GG! (Good Game and Great Grade!)",
        "You're the Minecraft master of this subject!",
        "You built a palace of correct answers.",
        "You've earned 1,000,000 V-Bucks of pure awesome!",
        "You're the 'Among Us' player who's definitely not the imposter, just the genius.",
        "You're the main character, and you just won.",
        "That was worthy of a TikTok dance trend.",
        "You didn't just pass the vibe check, you ARE the vibe.",
        "This performance is fire. No cap.",
        "You're officially trending for being awesome.",
        "You're the CEO of getting questions right.",
        "You're a living cheat code!",
        "That was cleaner than my search history.",
        "You're a certified boss.",
        "You've got the Midas touch for tests!",
        "You're a walking, talking encyclopedia!",
        "Your brain is working faster than the Flash.",
        "You're more powerful than a Super Saiyan!",
        "You just went Super Saiyan on that quiz!",
        "That's some next-level thinking.",
        "You're a history-maker!",
        "You're basically a unicorn: mythical and amazing.",
        "You're a human calculator!",
        "You're a spelling bee champion in the making.",
        "You've got a black belt in brilliance.",
        "You're a shooting star of success!",
        "You're a galaxy of greatness!",
        "You're a planet of perfection!",
        "You're an ocean of awesome!",
        "You're a mountain of mastery!",
        "You're a forest of fantastic facts!",
        "You're a river of right answers!",
        "You're a castle of correctness!",
        "You're a kingdom of knowledge!",
        "You're an empire of excellence!",
        "You're a universe of understanding!",
        "You're a dimension of distinction!",
        "Are you a 90-degree angle? Because that was right!",
        "You're not a photographer, but you pictured success and made it happen!",
        "That was a tree-mendous performance! You're unbe-leaf-able!",
        "You're so good, it's scary! You must be a 'boo-rilliant' student.",
        "This performance was bussin'! No cap.",
        "You ate that quiz and left no crumbs. Slay!",
        "That was a glow up for your brain. It's giving... genius.",
        "Big W. You understood the assignment.",
        "Bet. You're goated."
    ],
    good: [
        "Great job! You're really getting the hang of this.",
        "Solid work! Keep up the great effort.",
        "Nice! A little more practice and you'll be unstoppable.",
        "You're doing great! Every quiz makes you stronger.",
        "Awesome effort! You're on the right track.",
        "Very well done! Keep that momentum going.",
        "I can see you've been practicing. It shows!",
        "You're climbing that mountain! Keep going!",
        "The force is strong with this one.",
        "That's what I'm talking about! Nice one.",
        "You're assembling knowledge like an Avenger!",
        "You're in your training montage. Keep it up, Rocky!",
        "This is your superhero origin story. Keep training!",
        "You're leveling up! +10 XP in smarts!",
        "You're like a Jedi Padawan, on your way to mastery.",
        "You're not a rookie anymore. Great work!",
        "You're collecting those gold rings, Sonic-style!",
        "You're building something amazing, one block at a time. Just like in Minecraft!",
        "You're on a winning streak!",
        "That was a solid performance.",
        "You're a rising star!",
        "You've got a great foundation. Keep building!",
        "You're making fantastic progress.",
        "You're a quick learner!",
        "You're getting better every time.",
        "You're on the path to greatness.",
        "You're a true contender.",
        "You're a problem-solver in action.",
        "You're a thinker, and it shows.",
        "You're a dedicated learner.",
        "You're a diligent student.",
        "You're a hard worker, and it's paying off.",
        "You're a determined individual.",
        "You're a focused achiever.",
        "You're a goal-getter.",
        "You're a success story in the making.",
        "You're a future leader.",
        "You're a role model for others.",
        "You're an inspiration to us all.",
        "You're a beacon of light.",
        "You're a source of strength.",
        "You're a fountain of knowledge.",
        "You're a river of wisdom.",
        "You're an ocean of potential.",
        "You're a mountain of might.",
        "You're a forest of fortitude.",
        "You're a galaxy of growth.",
        "You're a universe of understanding.",
        "You're a dimension of development.",
        "You're a testament to trying.",
        "You're a monument to motivation.",
        "You're a pillar of persistence.",
        "You're a tower of tenacity.",
        "You're a fortress of fortitude.",
        "You're a castle of capabilities.",
        "You're a kingdom of confidence.",
        "You're an empire of effort.",
        "You're a dynasty of determination.",
        "You're a legacy of learning.",
        "You're a saga of success.",
        "You're a tale of triumph.",
        "You're a legend in the making.",
        "You're a hero in training.",
        "You're a warrior of wisdom.",
        "You're a champion of change.",
        "You're a master of motivation.",
        "You're a guru of growth.",
        "You're a sensei of success.",
        "You're a mentor of mastery.",
        "You're a coach of confidence.",
        "You're a captain of capabilities.",
        "You're a commander of comprehension.",
        "You're a general of genius.",
        "You're an admiral of achievement.",
        "You're a president of progress.",
        "You're a king of knowledge.",
        "You're a queen of quizzes.",
        "You're a prince of practice.",
        "You're a princess of persistence.",
        "You're a duke of dedication.",
        "You're a duchess of diligence.",
        "You're a baron of brilliance.",
        "You're a baroness of brains.",
        "You're a count of correctness.",
        "You're a countess of cleverness.",
        "You're a viscount of victory.",
        "You're a viscountess of valor.",
        "You're a marquis of merit.",
        "You're a marquise of mastery.",
        "You're an earl of excellence.",
        "You're a countess of competence.",
        "You're a lord of learning.",
        "You're a lady of logic.",
        "You're a sir of success.",
        "You're a dame of distinction.",
        "You're a knight of knowledge.",
        "You're a squire of smarts.",
        "Lettuce celebrate this great score!",
        "You're one smart cookie! Keep up the good work.",
        "You did a grape job! Keep it up!",
        "That was pretty lit. You're getting the hang of it.",
        "The vibes are immaculate. Good job.",
        "You're in your learning era, and it's iconic."
    ],
    keepTrying: [
        "Don't give up! Every mistake is a step forward.",
        "You've got this! Let's try it again.",
        "Practice makes perfect. You're on your way!",
        "Learning is a journey. Keep taking steps!",
        "Even superheroes have to train. You can do it!",
        "Failure is not the opposite of success, it's part of it.",
        "Do or do not. There is no try... so let's DO it again!",
        "I believe in you! Let's give it another go.",
        "Your comeback is going to be epic.",
        "Every master was once a beginner. Keep learning!",
        "This is just a side quest. The main adventure awaits!",
        "You just found the 'learning opportunity' power-up!",
        "It's okay! Even Ash Ketchum didn't win the Pokémon League at first.",
        "Respawning with more knowledge... now!",
        "Don't worry, even Mario falls down a pit sometimes. Time to jump back in!",
        "This is just a boss battle. You'll figure out the pattern!",
        "Why do we fall? So we can learn to pick ourselves up. - Alfred Pennyworth",
        "Never give up, never surrender! - Galaxy Quest",
        "A Jedi uses the Force for knowledge and defense. Time to re-focus.",
        "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
        "You're on a hero's journey, and every hero faces challenges.",
        "You haven't failed. You've just found 10,000 ways that won't work. - Thomas Edison",
        "The greatest teacher, failure is. - Yoda",
        "Don't be afraid to fail. Be afraid not to try.",
        "Every try is a step up the ladder.",
        "You're building your brain muscle!",
        "Challenges are what make life interesting.",
        "You're learning what to do by figuring out what not to do.",
        "This is how we get better!",
        "Mistakes are proof that you are trying.",
        "Growth is a process. Keep going.",
        "You've got the heart of a lion.",
        "You've got the eye of the tiger.",
        "You've got the courage of a Gryffindor.",
        "You've got the loyalty of a Hufflepuff.",
        "You've got the wisdom of a Ravenclaw.",
        "You've got the ambition of a Slytherin.",
        "You've got the strength of a hero.",
        "You've got the spirit of a champion.",
        "You've got the will of a warrior.",
        "You've got the mind of a master.",
        "You've got the soul of a scholar.",
        "You've got the heart of a learner.",
        "You've got the drive of a winner.",
        "You've got the focus of a ninja.",
        "You've got the dedication of a sensei.",
        "You've got the patience of a saint.",
        "You've got the persistence of a snail.",
        "You've got the resilience of a rubber band.",
        "You've got the adaptability of a chameleon.",
        "You've got the creativity of an artist.",
        "You've got the curiosity of a cat.",
        "You've got the bravery of a knight.",
        "You've got the honor of a samurai.",
        "You've got the discipline of a monk.",
        "You've got the determination of an Olympian.",
        "You've got the stamina of a marathoner.",
        "You've got the power of a locomotive.",
        "You've got the speed of a cheetah.",
        "You've got the grace of a gazelle.",
        "You've got the might of a mountain.",
        "You've got the depth of an ocean.",
        "You've got the breadth of a river.",
        "You've got the reach of a forest.",
        "You've got the height of a skyscraper.",
        "You've got the foundation of a pyramid.",
        "You've got the history of a civilization.",
        "You've got the future of a generation.",
        "You've got the potential of a seed.",
        "You've got the promise of a sunrise.",
        "You've got the hope of a rainbow.",
        "You've got the magic of a miracle.",
        "You've got the wonder of a wish.",
        "You've got the joy of a journey.",
        "You've got the thrill of a discovery.",
        "You've got the excitement of an adventure.",
        "You've got the challenge of a quest.",
        "You've got the reward of a treasure.",
        "You've got the prize of a victory.",
        "You've got the crown of a king.",
        "You've got the throne of a queen.",
        "You've got the kingdom of a conqueror.",
        "You've got the empire of an emperor.",
        "You've got the dynasty of a ruler.",
        "You've got the legacy of a legend.",
        "You've got the saga of a hero.",
        "You've got the tale of a triumph.",
        "You've got the story of a success.",
        "You've got the song of a siren.",
        "You've got the dance of a dervish.",
        "You've got the art of an artisan.",
        "You've got the craft of a craftsman.",
        "You've got the skill of a specialist.",
        "You've got the trade of a tradesman.",
        "You've got the profession of a professional.",
        "You've got the calling of a career.",
        "You've got the vocation of a virtuoso.",
        "Don't be salty about the score! You'll do better next time.",
        "Taco 'bout a comeback! Your next attempt will be amazing.",
        "This is just the first draft. The final version will be a masterpiece.",
        "It's giving... main character in a training arc.",
        "This ain't it, chief, but the next one will be.",
        "It's a canon event, you have to struggle before you succeed."
    ],
};

export const getEncouragement = (score: number, total: number): string => {
    if (total === 0) return "Let's get started!";
    const percentage = (score / total);

    let category: 'excellent' | 'good' | 'keepTrying';

    if (percentage >= 0.9) {
        category = 'excellent';
    } else if (percentage >= 0.6) {
        category = 'good';
    } else {
        category = 'keepTrying';
    }

    const messages = encouragement[category];
    const randomIndex = Math.floor(Math.random() * messages.length);
    return messages[randomIndex];
}
